name: Manage labels

on:
  push:
    branches:
      - main
      - master

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.6

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.1.0
        with:
          skip-delete: true
