---
name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release integration
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.6.0

      - name: Adjust version number
        shell: bash
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version,,}"
          version="${version#v}"
          yq e -P -o=json \
            -i ".version = \"${version}\"" \
            "${{ github.workspace }}/custom_components/energy_meter/manifest.json"

      - name: Create zipped release package
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/energy_meter"
          zip energy_meter.zip -r ./

      - name: Upload to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/energy_meter/energy_meter.zip
          asset_name: energy_meter.zip
          tag: ${{ github.ref }}
          overwrite: true
